version: '3'

services:

  selenium_firefox:
    image: selenium/standalone-firefox
    ports:
      - 127.0.0.1:4444:4444
    shm_size: "2g"
    
  selenium_chrome:
    image: selenium/standalone-chrome
    ports:
      - 127.0.0.1:5555:4444
    shm_size: "2g"
